### ISSUE TITLE
How to verify license file?

### ISSUE THREAD

**Issue by bushev** [nicroto/license-key#1]
Hello, Nikolay!

The documentation is clear state how to generate a license key. But I can't understand, how to verify these license file?

**Comment by nicroto** [comment]
Hi,

You need to learn how to sign information with openssl and a private key and then verify the signed with openssl and the public key on the customer's end.

Basically, the produced license text contains all the information that you need to reconstruct the **signed** chunk of text. Once you parse the license key on the customer's end, you reconstruct the signed text and verify this same text was signed with the private key. You do the verification using the public key.

complexCheckOfCustomerData

**Comment by bushev** [comment]
Hi!

Based on your idea, I have created a similar one License file generator and parser with ability of content validation.

https://github.com/bushev/nodejs-license-file
